# Generated by Django 6.0.2 on 2026-02-25 05:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excellent_count', models.PositiveIntegerField(default=0, verbose_name='Количество отличников')),
                ('good_count', models.PositiveIntegerField(default=0, verbose_name='Количество ударников')),
                ('one_four_count', models.PositiveIntegerField(default=0, verbose_name='С одной "4"')),
                ('one_three_count', models.PositiveIntegerField(default=0, verbose_name='С одной "3"')),
                ('poor_count', models.PositiveIntegerField(default=0, verbose_name='Количество двоечников')),
                ('not_attested_count', models.PositiveIntegerField(default=0, verbose_name='Не аттестованы')),
                ('retained_count', models.PositiveIntegerField(default=0, verbose_name='Оставлены на повторный год')),
                ('conditionally_promoted_count', models.PositiveIntegerField(default=0, verbose_name='Переведены условно')),
                ('days_missed', models.PositiveIntegerField(default=0, verbose_name='Пропущено учебных дней')),
                ('days_missed_illness', models.PositiveIntegerField(default=0, verbose_name='из них по болезни')),
                ('lessons_missed', models.PositiveIntegerField(default=0, verbose_name='Пропущено уроков всего')),
                ('lessons_missed_illness', models.PositiveIntegerField(default=0, verbose_name='из них по болезни')),
                ('injury_school', models.PositiveIntegerField(default=0, verbose_name='Травматизм в школе')),
                ('injury_outside', models.PositiveIntegerField(default=0, verbose_name='Травматизм вне школы')),
            ],
            options={
                'verbose_name': 'Успеваемость',
                'verbose_name_plural': 'Успеваемость',
            },
        ),
        migrations.CreateModel(
            name='FamilyEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_family_education', models.BooleanField(default=False, verbose_name='Есть ученики на семейном обучении')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Семейное обучение',
                'verbose_name_plural': 'Семейное обучение',
            },
        ),
        migrations.CreateModel(
            name='PhysicalEducationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_group', models.PositiveIntegerField(default=0, verbose_name='Основная группа')),
                ('preparatory_group', models.PositiveIntegerField(default=0, verbose_name='Подготовительная группа')),
                ('special_group', models.PositiveIntegerField(default=0, verbose_name='Специальная группа')),
                ('exempt_count', models.PositiveIntegerField(default=0, verbose_name='Освобождены')),
            ],
            options={
                'verbose_name': 'Физкультурная группа',
                'verbose_name_plural': 'Физкультурные группы',
            },
        ),
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название периода')),
                ('period_type', models.CharField(choices=[('start_year', 'Начало учебного года'), ('quarter1', '1 четверть'), ('quarter2', '2 четверть'), ('quarter3', '3 четверть'), ('quarter4', '4 четверть'), ('half1', '1 полугодие'), ('half2', '2 полугодие'), ('year', 'Год')], max_length=20, verbose_name='Тип периода')),
                ('academic_year', models.CharField(max_length=9, verbose_name='Учебный год')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Отчетный период',
                'verbose_name_plural': 'Отчетные периоды',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название класса')),
                ('parallel', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Параллель')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['parallel', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled_count', models.PositiveIntegerField(default=0, verbose_name='Дети-инвалиды')),
                ('special_needs_count', models.PositiveIntegerField(default=0, verbose_name='Дети с ОВЗ')),
                ('disabled_special_needs_count', models.PositiveIntegerField(default=0, verbose_name='Дети-инвалиды с ОВЗ')),
                ('home_schooling_count', models.PositiveIntegerField(default=0, verbose_name='Обучающиеся на дому')),
                ('home_schooling_disabled_count', models.PositiveIntegerField(default=0, verbose_name='из них дети-инвалиды')),
                ('foster_care_count', models.PositiveIntegerField(default=0, verbose_name='Опекаемые дети')),
            ],
            options={
                'verbose_name': 'Дети с ОВЗ/инвалиды',
                'verbose_name_plural': 'Дети с ОВЗ/инвалиды',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('teacher', 'Учитель'), ('head_teacher', 'Завуч'), ('both', 'Учитель и Завуч')], default='teacher', max_length=20, verbose_name='Роль')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConditionallyPromotedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО ученика')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditionally_promoted_students', to='reports.academicperformance', verbose_name='Успеваемость')),
            ],
            options={
                'verbose_name': 'Переведенный условно',
                'verbose_name_plural': 'Переведенные условно',
            },
        ),
        migrations.CreateModel(
            name='ExcellentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО ученика')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excellent_students', to='reports.academicperformance', verbose_name='Успеваемость')),
            ],
            options={
                'verbose_name': 'Отличник',
                'verbose_name_plural': 'Отличники',
            },
        ),
        migrations.CreateModel(
            name='FamilyEducationStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО ученика')),
                ('family_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='reports.familyeducation', verbose_name='Семейное обучение')),
            ],
            options={
                'verbose_name': 'Ученик на семейном обучении',
                'verbose_name_plural': 'Ученики на семейном обучении',
            },
        ),
        migrations.CreateModel(
            name='NotAttestedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО ученика')),
                ('subjects', models.TextField(verbose_name='Предметы с указанием учителей')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_attested_students', to='reports.academicperformance', verbose_name='Успеваемость')),
            ],
            options={
                'verbose_name': 'Не аттестованный ученик',
                'verbose_name_plural': 'Не аттестованные ученики',
            },
        ),
        migrations.CreateModel(
            name='OneFourStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО ученика')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('subject_code', models.CharField(blank=True, max_length=50, verbose_name='Код предмета')),
                ('teacher', models.CharField(max_length=100, verbose_name='Учитель')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_four_students', to='reports.academicperformance', verbose_name='Успеваемость')),
            ],
            options={
                'verbose_name': 'Ученик с одной "4"',
                'verbose_name_plural': 'Ученики с одной "4"',
            },
        ),
        migrations.CreateModel(
            name='OneThreeStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО ученика')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('subject_code', models.CharField(blank=True, max_length=50, verbose_name='Код предмета')),
                ('teacher', models.CharField(max_length=100, verbose_name='Учитель')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_three_students', to='reports.academicperformance', verbose_name='Успеваемость')),
            ],
            options={
                'verbose_name': 'Ученик с одной "3"',
                'verbose_name_plural': 'Ученики с одной "3"',
            },
        ),
        migrations.CreateModel(
            name='ExemptStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО ученика')),
                ('phys_ed_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exempt_students', to='reports.physicaleducationgroup', verbose_name='Физгруппа')),
            ],
            options={
                'verbose_name': 'Освобожденный ученик',
                'verbose_name_plural': 'Освобожденные ученики',
            },
        ),
        migrations.CreateModel(
            name='PoorStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО ученика')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('subject_code', models.CharField(blank=True, max_length=50, verbose_name='Код предмета')),
                ('teacher', models.CharField(max_length=100, verbose_name='Учитель')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Сквозная двойка')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poor_students', to='reports.academicperformance', verbose_name='Успеваемость')),
            ],
            options={
                'verbose_name': 'Двоечник',
                'verbose_name_plural': 'Двоечники',
            },
        ),
        migrations.CreateModel(
            name='RetainedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО ученика')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retained_students', to='reports.academicperformance', verbose_name='Успеваемость')),
            ],
            options={
                'verbose_name': 'Оставленный на повторный год',
                'verbose_name_plural': 'Оставленные на повторный год',
            },
        ),
        migrations.CreateModel(
            name='SpecialNeedsStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('disabled', 'Дети-инвалиды'), ('special_needs', 'Дети с ОВЗ'), ('disabled_special', 'Дети-инвалиды с ОВЗ'), ('home_schooling', 'Обучающиеся на дому'), ('home_disabled', 'Обучающиеся на дому (инвалиды)'), ('foster_care', 'Опекаемые дети')], max_length=20, verbose_name='Тип')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО ученика')),
                ('special_needs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='reports.specialneeds', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ученик особой категории',
                'verbose_name_plural': 'Ученики особых категорий',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('homeroom_classes', models.ManyToManyField(blank=True, related_name='homeroom_teachers', to='reports.schoolclass', verbose_name='Классное руководство')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='TeacherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлен'), ('approved', 'Утвержден'), ('rejected', 'Отклонен')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
                ('total_students_end', models.PositiveIntegerField(default=0, verbose_name='Количество учеников на конец периода')),
                ('has_movement', models.BooleanField(default=False, verbose_name='Есть движение учеников')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reportperiod', verbose_name='Период')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.schoolclass', verbose_name='Класс')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Отчет учителя',
                'verbose_name_plural': 'Отчеты учителей',
            },
        ),
        migrations.CreateModel(
            name='StudentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Прибыл'), ('out', 'Выбыл')], max_length=3, verbose_name='Тип движения')),
                ('student_name', models.CharField(max_length=100, verbose_name='ФИО ученика')),
                ('moved_to_another_class', models.BooleanField(default=False, verbose_name='Выбыл в другой класс')),
                ('moved_to_another_school', models.BooleanField(default=False, verbose_name='Выбыл в другую школу')),
                ('target_school', models.CharField(blank=True, max_length=200, verbose_name='Школа')),
                ('came_from_another_class', models.BooleanField(default=False, verbose_name='Прибыл из другого класса')),
                ('came_from_another_school', models.BooleanField(default=False, verbose_name='Прибыл из другой школы')),
                ('source_school', models.CharField(blank=True, max_length=200, verbose_name='Школа')),
                ('order_number', models.CharField(max_length=50, verbose_name='Номер приказа')),
                ('order_date', models.DateField(verbose_name='Дата приказа')),
                ('source_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reports.schoolclass', verbose_name='Класс')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.schoolclass', verbose_name='Класс')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='reports.teacherreport', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Движение ученика',
                'verbose_name_plural': 'Движения учеников',
            },
        ),
        migrations.CreateModel(
            name='StudentAgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField(verbose_name='Год рождения')),
                ('boys_count', models.PositiveIntegerField(default=0, verbose_name='Мальчики')),
                ('girls_count', models.PositiveIntegerField(default=0, verbose_name='Девочки')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_groups', to='reports.teacherreport', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Возрастная группа',
                'verbose_name_plural': 'Возрастные группы',
            },
        ),
        migrations.AddField(
            model_name='specialneeds',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_needs', to='reports.teacherreport', verbose_name='Отчет'),
        ),
        migrations.AddField(
            model_name='physicaleducationgroup',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phys_ed_groups', to='reports.teacherreport', verbose_name='Отчет'),
        ),
        migrations.CreateModel(
            name='HealthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group1', models.PositiveIntegerField(default=0, verbose_name='1 группа')),
                ('group2', models.PositiveIntegerField(default=0, verbose_name='2 группа')),
                ('group3', models.PositiveIntegerField(default=0, verbose_name='3 группа')),
                ('group4', models.PositiveIntegerField(default=0, verbose_name='4 группа')),
                ('group5', models.PositiveIntegerField(default=0, verbose_name='5 группа')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_groups', to='reports.teacherreport', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Группа здоровья',
                'verbose_name_plural': 'Группы здоровья',
            },
        ),
        migrations.AddField(
            model_name='familyeducation',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_education', to='reports.teacherreport', verbose_name='Отчет'),
        ),
        migrations.AddField(
            model_name='academicperformance',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_performance', to='reports.teacherreport', verbose_name='Отчет'),
        ),
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9, verbose_name='Учебный год')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Дата назначения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.schoolclass', verbose_name='Класс')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='reports.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Назначение класса',
                'verbose_name_plural': 'Назначения классов',
                'unique_together': {('teacher', 'school_class', 'academic_year')},
            },
        ),
        migrations.AddIndex(
            model_name='teacherreport',
            index=models.Index(fields=['teacher', 'period'], name='reports_tea_teacher_b50a23_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherreport',
            index=models.Index(fields=['school_class', 'period'], name='reports_tea_school__5466ad_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherreport',
            index=models.Index(fields=['status'], name='reports_tea_status_65affd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherreport',
            unique_together={('teacher', 'school_class', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='studentagegroup',
            unique_together={('report', 'birth_year')},
        ),
    ]
