# Generated by Django 6.0.2 on 2026-03-02 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmovement',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приказа'),
        ),
        migrations.AlterField(
            model_name='studentmovement',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер приказа'),
        ),
        migrations.AlterField(
            model_name='studentmovement',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reports.schoolclass', verbose_name='Класс'),
        ),
    ]
