# Generated by Django 6.0.2 on 2026-03-05 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_studentmovement_order_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyeducationstudent',
            options={'ordering': ['full_name'], 'verbose_name': 'Ученик на семейном обучении', 'verbose_name_plural': 'Ученики на семейном обучении'},
        ),
        migrations.AddField(
            model_name='familyeducationstudent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
