# Generated by Django 6.0.2 on 2026-03-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_familyeducationstudent_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportperiod',
            unique_together={('period_type', 'academic_year')},
        ),
    ]
