# Generated by Django 6.0.2 on 2026-03-11 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reportperiod_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherclassassignment',
            options={'ordering': ['academic_year', 'school_class__parallel', 'school_class__name'], 'verbose_name': 'Назначение класса', 'verbose_name_plural': 'Назначения классов'},
        ),
        migrations.AlterField(
            model_name='teacherclassassignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='reports.schoolclass', verbose_name='Класс'),
        ),
    ]
